[package]
name = "rust-kanban"
version = "0.9.3"
authors = ["Yash Sharma <yashs662@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/yashs662/rust_kanban"
description = "A kanban board for the terminal built with ❤️ in Rust"
keywords = ["TUI", "Kanban", "CLI", "Terminal"]
categories = ["command-line-utilities", "text-editors"]

[dependencies]
log = "0.4.20"
ratatui = { version = "0.26.1", features = ["serde"] }
crossterm = "0.27.0"
tokio = { version = "1.36.0", features = ["full"] }
chrono = "0.4.34"
textwrap = "0.16"
eyre = "0.6.12"
home = "0.5.9"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
clap = { version = "4.5.1", features = ["derive"] }
uuid = { version = "1.7.0", features = ["v4"] }
regex = "1.10.3"
linked-hash-map = "0.5.6"
ngrammatic = "0.4.0"
lazy_static = "1.4.0"
fxhash = "0.2.1"
parking_lot = "0.12.1"
reqwest = { version = "0.11.24", features = ["json"] }
aes-gcm = "0.10.3"
base64 = "0.21.7"
bunt = "0.2.8"
strum = "0.26.1"
strum_macros = "0.26.1"
