[package]
name = "rust-kanban"
version = "0.7.2"
authors = ["Yash Sharma <yashs662@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/yashs662/rust_kanban"
description = "A kanban board for the terminal built with ❤️ in Rust"
keywords = ["TUI", "Kanban", "CLI", "Terminal"]
categories = ["command-line-utilities", "text-editors"]

[dependencies]
log = { version = "0.4.19", features = [
    "max_level_debug",
    "release_max_level_info"
] }
ratatui = { version = "0.22.0", features = ["serde"] }
crossterm = "0.26.1"
tokio = { version = "1.29.1", features = ["full"] }
chrono = "0.4.26"
textwrap = "0.16"
eyre = "0.6.8"
home = "0.5.5"
serde = { version = "1.0.175", features = ["derive"] }
serde_json = "1.0.103"
clap = { version = "4.3.19", features = ["derive"] }
uuid = { version = "1.4.1", features = ["v4"] }
regex = "1.9.1"
linked-hash-map = "0.5.6"
ngrammatic = "0.4.0"
lazy_static = "1.4.0"
fxhash = "0.2.1"
parking_lot = "0.12.1"
reqwest = { version = "0.11.18", features = ["json"] }
aes-gcm = "0.10.2"
base64 = "0.21.2"
bunt = "0.2.8"
