[package]
name = "rust-kanban"
version = "0.9.1"
authors = ["Yash Sharma <yashs662@gmail.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/yashs662/rust_kanban"
description = "A kanban board for the terminal built with ❤️ in Rust"
keywords = ["TUI", "Kanban", "CLI", "Terminal"]
categories = ["command-line-utilities", "text-editors"]

[dependencies]
log = "0.4.20"
ratatui = { version = "0.25.0", features = ["serde"] }
crossterm = "0.27.0"
tokio = { version = "1.35.1", features = ["full"] }
chrono = "0.4.31"
textwrap = "0.16"
eyre = "0.6.11"
home = "0.5.9"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
clap = { version = "4.4.14", features = ["derive"] }
uuid = { version = "1.6.1", features = ["v4"] }
regex = "1.10.2"
linked-hash-map = "0.5.6"
ngrammatic = "0.4.0"
lazy_static = "1.4.0"
fxhash = "0.2.1"
parking_lot = "0.12.1"
reqwest = { version = "0.11.23", features = ["json"] }
aes-gcm = "0.10.3"
base64 = "0.21.6"
bunt = "0.2.8"
